// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protocols/isis/api/isis.proto

package api

import (
	api "github.com/bio-routing/bio-rd/net/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Adjacency_State int32

const (
	Adjacency_Down Adjacency_State = 0
	Adjacency_Init Adjacency_State = 1
	Adjacency_Up   Adjacency_State = 2
)

// Enum value maps for Adjacency_State.
var (
	Adjacency_State_name = map[int32]string{
		0: "Down",
		1: "Init",
		2: "Up",
	}
	Adjacency_State_value = map[string]int32{
		"Down": 0,
		"Init": 1,
		"Up":   2,
	}
)

func (x Adjacency_State) Enum() *Adjacency_State {
	p := new(Adjacency_State)
	*p = x
	return p
}

func (x Adjacency_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Adjacency_State) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_isis_api_isis_proto_enumTypes[0].Descriptor()
}

func (Adjacency_State) Type() protoreflect.EnumType {
	return &file_protocols_isis_api_isis_proto_enumTypes[0]
}

func (x Adjacency_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Adjacency_State.Descriptor instead.
func (Adjacency_State) EnumDescriptor() ([]byte, []int) {
	return file_protocols_isis_api_isis_proto_rawDescGZIP(), []int{2, 0}
}

type ListAdjacenciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdjacenciesRequest) Reset() {
	*x = ListAdjacenciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_isis_api_isis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdjacenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdjacenciesRequest) ProtoMessage() {}

func (x *ListAdjacenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_isis_api_isis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdjacenciesRequest.ProtoReflect.Descriptor instead.
func (*ListAdjacenciesRequest) Descriptor() ([]byte, []int) {
	return file_protocols_isis_api_isis_proto_rawDescGZIP(), []int{0}
}

type ListAdjacenciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adjacencies []*Adjacency `protobuf:"bytes,1,rep,name=adjacencies,proto3" json:"adjacencies,omitempty"`
}

func (x *ListAdjacenciesResponse) Reset() {
	*x = ListAdjacenciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_isis_api_isis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdjacenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdjacenciesResponse) ProtoMessage() {}

func (x *ListAdjacenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_isis_api_isis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdjacenciesResponse.ProtoReflect.Descriptor instead.
func (*ListAdjacenciesResponse) Descriptor() ([]byte, []int) {
	return file_protocols_isis_api_isis_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdjacenciesResponse) GetAdjacencies() []*Adjacency {
	if x != nil {
		return x.Adjacencies
	}
	return nil
}

type Adjacency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SystemId           []byte          `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Address            []byte          `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	InterfaceName      string          `protobuf:"bytes,4,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`
	Level              uint32          `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Priority           uint32          `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	IpAddresses        []*api.IP       `protobuf:"bytes,7,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	LastTransitionUnix int64           `protobuf:"varint,8,opt,name=last_transition_unix,json=lastTransitionUnix,proto3" json:"last_transition_unix,omitempty"`
	ExpiresInSeconds   uint32          `protobuf:"varint,9,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	Status             Adjacency_State `protobuf:"varint,10,opt,name=status,proto3,enum=bio.isis.Adjacency_State" json:"status,omitempty"`
}

func (x *Adjacency) Reset() {
	*x = Adjacency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_isis_api_isis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Adjacency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adjacency) ProtoMessage() {}

func (x *Adjacency) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_isis_api_isis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adjacency.ProtoReflect.Descriptor instead.
func (*Adjacency) Descriptor() ([]byte, []int) {
	return file_protocols_isis_api_isis_proto_rawDescGZIP(), []int{2}
}

func (x *Adjacency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Adjacency) GetSystemId() []byte {
	if x != nil {
		return x.SystemId
	}
	return nil
}

func (x *Adjacency) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Adjacency) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Adjacency) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Adjacency) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Adjacency) GetIpAddresses() []*api.IP {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *Adjacency) GetLastTransitionUnix() int64 {
	if x != nil {
		return x.LastTransitionUnix
	}
	return 0
}

func (x *Adjacency) GetExpiresInSeconds() uint32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *Adjacency) GetStatus() Adjacency_State {
	if x != nil {
		return x.Status
	}
	return Adjacency_Down
}

var File_protocols_isis_api_isis_proto protoreflect.FileDescriptor

var file_protocols_isis_api_isis_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x69, 0x73, 0x69, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x62, 0x69, 0x6f, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x1a, 0x11, 0x6e, 0x65, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6e, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x69, 0x6f, 0x2e, 0x69, 0x73, 0x69,
	0x73, 0x2e, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0b, 0x61, 0x64, 0x6a,
	0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x22, 0x96, 0x03, 0x0a, 0x09, 0x41, 0x64, 0x6a,
	0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x0c, 0x69, 0x70, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x62, 0x69, 0x6f, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x49, 0x50, 0x52, 0x0b, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x6e, 0x69,
	0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x69, 0x6f, 0x2e,
	0x69, 0x73, 0x69, 0x73, 0x2e, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x23, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x70, 0x10,
	0x02, 0x32, 0x67, 0x0a, 0x0b, 0x49, 0x73, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x58, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x62, 0x69, 0x6f, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x69, 0x6f, 0x2e, 0x69, 0x73, 0x69, 0x73,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x6a, 0x61, 0x63, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x6f, 0x2d, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x69, 0x6f, 0x2d, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x69, 0x73, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_isis_api_isis_proto_rawDescOnce sync.Once
	file_protocols_isis_api_isis_proto_rawDescData = file_protocols_isis_api_isis_proto_rawDesc
)

func file_protocols_isis_api_isis_proto_rawDescGZIP() []byte {
	file_protocols_isis_api_isis_proto_rawDescOnce.Do(func() {
		file_protocols_isis_api_isis_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_isis_api_isis_proto_rawDescData)
	})
	return file_protocols_isis_api_isis_proto_rawDescData
}

var file_protocols_isis_api_isis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocols_isis_api_isis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocols_isis_api_isis_proto_goTypes = []interface{}{
	(Adjacency_State)(0),            // 0: bio.isis.Adjacency.State
	(*ListAdjacenciesRequest)(nil),  // 1: bio.isis.ListAdjacenciesRequest
	(*ListAdjacenciesResponse)(nil), // 2: bio.isis.ListAdjacenciesResponse
	(*Adjacency)(nil),               // 3: bio.isis.Adjacency
	(*api.IP)(nil),                  // 4: bio.net.IP
}
var file_protocols_isis_api_isis_proto_depIdxs = []int32{
	3, // 0: bio.isis.ListAdjacenciesResponse.adjacencies:type_name -> bio.isis.Adjacency
	4, // 1: bio.isis.Adjacency.ip_addresses:type_name -> bio.net.IP
	0, // 2: bio.isis.Adjacency.status:type_name -> bio.isis.Adjacency.State
	1, // 3: bio.isis.IsisService.ListAdjacencies:input_type -> bio.isis.ListAdjacenciesRequest
	2, // 4: bio.isis.IsisService.ListAdjacencies:output_type -> bio.isis.ListAdjacenciesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protocols_isis_api_isis_proto_init() }
func file_protocols_isis_api_isis_proto_init() {
	if File_protocols_isis_api_isis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_isis_api_isis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdjacenciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_isis_api_isis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdjacenciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_isis_api_isis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Adjacency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_isis_api_isis_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocols_isis_api_isis_proto_goTypes,
		DependencyIndexes: file_protocols_isis_api_isis_proto_depIdxs,
		EnumInfos:         file_protocols_isis_api_isis_proto_enumTypes,
		MessageInfos:      file_protocols_isis_api_isis_proto_msgTypes,
	}.Build()
	File_protocols_isis_api_isis_proto = out.File
	file_protocols_isis_api_isis_proto_rawDesc = nil
	file_protocols_isis_api_isis_proto_goTypes = nil
	file_protocols_isis_api_isis_proto_depIdxs = nil
}
