// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// DO NOT EDIT: this file is automatically generated by docgen
package config

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var ConfigDoc encoder.Doc

func init() {
	ConfigDoc.Type = "Config"
	ConfigDoc.Comments[encoder.LineComment] = ""
	ConfigDoc.Description = ""
	ConfigDoc.Fields = make([]encoder.Doc, 4)
	ConfigDoc.Fields[0].Name = "policy_options"
	ConfigDoc.Fields[0].Type = "PolicyOptions"
	ConfigDoc.Fields[0].Note = ""
	ConfigDoc.Fields[0].Description = "A list of policy statements, filters and prefix lists that can be used to filter route imports and exports.\n<a href=\"policy.md\">Detailed documentation</a>\nExample:\npolicy_statements:\n  - name: \"PeerA-In\"\n      terms:\n        - name: \"Reject_certain_stuff\"\n          from:\n            route_filters:\n               - prefix: \"198.51.100.0/24\"\n                 matcher: \"orlonger\"\n               - prefix: \"203.0.113.0/25\"\n                 matcher: \"exact\"\n               - prefix: \"203.0.113.128/25\"\n                 matcher: \"exact\""
	ConfigDoc.Fields[0].Comments[encoder.LineComment] = "A list of policy statements, filters and prefix lists that can be used to filter route imports and exports."
	ConfigDoc.Fields[1].Name = "routing_instances"
	ConfigDoc.Fields[1].Type = "[]RoutingInstance"
	ConfigDoc.Fields[1].Note = ""
	ConfigDoc.Fields[1].Description = "List of routing instances\n<a href=\"routing_instance.md\">Configuration parameters</a>"
	ConfigDoc.Fields[1].Comments[encoder.LineComment] = "List of routing instances"
	ConfigDoc.Fields[2].Name = "routing_options"
	ConfigDoc.Fields[2].Type = "RoutingOptions"
	ConfigDoc.Fields[2].Note = ""
	ConfigDoc.Fields[2].Description = "Routing options\n<a href=\"routing_options.md\">parameter documentation</a>\nAllowed values:\n- <a href=\"static_route.md\">static_routes</a>\n- router_id\n- autonomous_system"
	ConfigDoc.Fields[2].Comments[encoder.LineComment] = "Routing options"
	ConfigDoc.Fields[3].Name = "protocols"
	ConfigDoc.Fields[3].Type = "Protocols"
	ConfigDoc.Fields[3].Note = ""
	ConfigDoc.Fields[3].Description = "Here you define the specific configuration parameters for each protocol.\n<a href=\"protocols.md\">documentation</a>\nAvailable protocols:\n  - <a href=\"bgp.md\">bgp</a>\n  - <a href=\"isis.md\">is-is</a>"
	ConfigDoc.Fields[3].Comments[encoder.LineComment] = "Here you define the specific configuration parameters for each protocol."
}

func (_ Config) Doc() *encoder.Doc {
	return &ConfigDoc
}

// GetconfigDoc returns documentation for the file cmd/bio-rd/config/config_docs.go.
func GetconfigDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "config",
		Description: "",
		Structs: []*encoder.Doc{
			&ConfigDoc,
		},
	}
}
