// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// DO NOT EDIT: this file is automatically generated by docgen
package config

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var ProtocolsDoc encoder.Doc

func init() {
	ProtocolsDoc.Type = "Protocols"
	ProtocolsDoc.Comments[encoder.LineComment] = ""
	ProtocolsDoc.Description = ""
	ProtocolsDoc.Fields = make([]encoder.Doc, 2)
	ProtocolsDoc.Fields[0].Name = "bgp"
	ProtocolsDoc.Fields[0].Type = "BGP"
	ProtocolsDoc.Fields[0].Note = ""
	ProtocolsDoc.Fields[0].Description = "parameters for the bgp. See bgp.md file for details"
	ProtocolsDoc.Fields[0].Comments[encoder.LineComment] = "parameters for the bgp. See bgp.md file for details"
	ProtocolsDoc.Fields[1].Name = "isis"
	ProtocolsDoc.Fields[1].Type = "ISIS"
	ProtocolsDoc.Fields[1].Note = ""
	ProtocolsDoc.Fields[1].Description = "parameters for the is-is protocol. See is-is.md for details"
	ProtocolsDoc.Fields[1].Comments[encoder.LineComment] = "parameters for the is-is protocol. See is-is.md for details"
}

func (_ Protocols) Doc() *encoder.Doc {
	return &ProtocolsDoc
}

// GetprotocolsDoc returns documentation for the file cmd/bio-rd/config/protocols_docs.go.
func GetprotocolsDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "protocols",
		Description: "",
		Structs: []*encoder.Doc{
			&ProtocolsDoc,
		},
	}
}
