// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// DO NOT EDIT: this file is automatically generated by docgen
package config

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var RoutingInstanceDoc encoder.Doc

func init() {
	RoutingInstanceDoc.Type = "RoutingInstance"
	RoutingInstanceDoc.Comments[encoder.LineComment] = ""
	RoutingInstanceDoc.Description = ""
	RoutingInstanceDoc.Fields = make([]encoder.Doc, 4)
	RoutingInstanceDoc.Fields[0].Name = "name"
	RoutingInstanceDoc.Fields[0].Type = "string"
	RoutingInstanceDoc.Fields[0].Note = ""
	RoutingInstanceDoc.Fields[0].Description = "Name of the routing instance"
	RoutingInstanceDoc.Fields[0].Comments[encoder.LineComment] = "Name of the routing instance"
	RoutingInstanceDoc.Fields[1].Name = "route_distinguisher"
	RoutingInstanceDoc.Fields[1].Type = "string"
	RoutingInstanceDoc.Fields[1].Note = ""
	RoutingInstanceDoc.Fields[1].Description = "String to be used as a route distinguisher.\nThe format has to be <uint32>:<uint32>. Using IP addresses is *not* allowed"
	RoutingInstanceDoc.Fields[1].Comments[encoder.LineComment] = "String to be used as a route distinguisher."
	RoutingInstanceDoc.Fields[2].Name = "routing_options"
	RoutingInstanceDoc.Fields[2].Type = "RoutingOptions"
	RoutingInstanceDoc.Fields[2].Note = ""
	RoutingInstanceDoc.Fields[2].Description = "Routing options for this routing instance. See main config documentation for details"
	RoutingInstanceDoc.Fields[2].Comments[encoder.LineComment] = "Routing options for this routing instance. See main config documentation for details"
	RoutingInstanceDoc.Fields[3].Name = "protocols"
	RoutingInstanceDoc.Fields[3].Type = "Protocols"
	RoutingInstanceDoc.Fields[3].Note = ""
	RoutingInstanceDoc.Fields[3].Description = "Protocols for this routing instance. See the main protocols documentation for details"
	RoutingInstanceDoc.Fields[3].Comments[encoder.LineComment] = "Protocols for this routing instance. See the main protocols documentation for details"
}

func (_ RoutingInstance) Doc() *encoder.Doc {
	return &RoutingInstanceDoc
}

// Getrouting_instanceDoc returns documentation for the file cmd/bio-rd/config/routing_instance_docs.go.
func Getrouting_instanceDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "routing_instance",
		Description: "",
		Structs: []*encoder.Doc{
			&RoutingInstanceDoc,
		},
	}
}
