// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// DO NOT EDIT: this file is automatically generated by docgen
package config

import (
	"github.com/projectdiscovery/yamldoc-go/encoder"
)

var StaticRouteDoc encoder.Doc

func init() {
	StaticRouteDoc.Type = "StaticRoute"
	StaticRouteDoc.Comments[encoder.LineComment] = ""
	StaticRouteDoc.Description = ""
	StaticRouteDoc.Fields = make([]encoder.Doc, 4)
	StaticRouteDoc.Fields[0].Name = "prefix"
	StaticRouteDoc.Fields[0].Type = "string"
	StaticRouteDoc.Fields[0].Note = ""
	StaticRouteDoc.Fields[0].Description = "Prefix for the route"
	StaticRouteDoc.Fields[0].Comments[encoder.LineComment] = "Prefix for the route"
	StaticRouteDoc.Fields[1].Name = "discard"
	StaticRouteDoc.Fields[1].Type = "bool"
	StaticRouteDoc.Fields[1].Note = ""
	StaticRouteDoc.Fields[1].Description = "Makes this route a blackhole"
	StaticRouteDoc.Fields[1].Comments[encoder.LineComment] = "Makes this route a blackhole"
	StaticRouteDoc.Fields[2].Name = "next_hop"
	StaticRouteDoc.Fields[2].Type = "string"
	StaticRouteDoc.Fields[2].Note = ""
	StaticRouteDoc.Fields[2].Description = "Next hop for the route"
	StaticRouteDoc.Fields[2].Comments[encoder.LineComment] = "Next hop for the route"
	StaticRouteDoc.Fields[3].Name = "resolve"
	StaticRouteDoc.Fields[3].Type = "bool"
	StaticRouteDoc.Fields[3].Note = ""
	StaticRouteDoc.Fields[3].Description = "??"
	StaticRouteDoc.Fields[3].Comments[encoder.LineComment] = "??"
}

func (_ StaticRoute) Doc() *encoder.Doc {
	return &StaticRouteDoc
}

// Getstatic_routeDoc returns documentation for the file cmd/bio-rd/config/static_route_docs.go.
func Getstatic_routeDoc() *encoder.FileDoc {
	return &encoder.FileDoc{
		Name:        "static_route",
		Description: "",
		Structs: []*encoder.Doc{
			&StaticRouteDoc,
		},
	}
}
