// Code generated by protoc-gen-go. DO NOT EDIT.
// source: net/api/net.proto

package api // import "net/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IP_Version int32

const (
	IP_IPv4 IP_Version = 0
	IP_IPv6 IP_Version = 1
)

var IP_Version_name = map[int32]string{
	0: "IPv4",
	1: "IPv6",
}
var IP_Version_value = map[string]int32{
	"IPv4": 0,
	"IPv6": 1,
}

func (x IP_Version) String() string {
	return proto.EnumName(IP_Version_name, int32(x))
}
func (IP_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_net_6a797cde5ca49adf, []int{1, 0}
}

type Prefix struct {
	Address              *IP      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pfxlen               uint32   `protobuf:"varint,2,opt,name=pfxlen,proto3" json:"pfxlen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_net_6a797cde5ca49adf, []int{0}
}
func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (dst *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(dst, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetAddress() *IP {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Prefix) GetPfxlen() uint32 {
	if m != nil {
		return m.Pfxlen
	}
	return 0
}

type IP struct {
	Higher               uint64     `protobuf:"varint,1,opt,name=higher,proto3" json:"higher,omitempty"`
	Lower                uint64     `protobuf:"varint,2,opt,name=lower,proto3" json:"lower,omitempty"`
	Version              IP_Version `protobuf:"varint,3,opt,name=version,proto3,enum=bio.net.IP_Version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IP) Reset()         { *m = IP{} }
func (m *IP) String() string { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()    {}
func (*IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_net_6a797cde5ca49adf, []int{1}
}
func (m *IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IP.Unmarshal(m, b)
}
func (m *IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IP.Marshal(b, m, deterministic)
}
func (dst *IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IP.Merge(dst, src)
}
func (m *IP) XXX_Size() int {
	return xxx_messageInfo_IP.Size(m)
}
func (m *IP) XXX_DiscardUnknown() {
	xxx_messageInfo_IP.DiscardUnknown(m)
}

var xxx_messageInfo_IP proto.InternalMessageInfo

func (m *IP) GetHigher() uint64 {
	if m != nil {
		return m.Higher
	}
	return 0
}

func (m *IP) GetLower() uint64 {
	if m != nil {
		return m.Lower
	}
	return 0
}

func (m *IP) GetVersion() IP_Version {
	if m != nil {
		return m.Version
	}
	return IP_IPv4
}

func init() {
	proto.RegisterType((*Prefix)(nil), "bio.net.Prefix")
	proto.RegisterType((*IP)(nil), "bio.net.IP")
	proto.RegisterEnum("bio.net.IP_Version", IP_Version_name, IP_Version_value)
}

func init() { proto.RegisterFile("net/api/net.proto", fileDescriptor_net_6a797cde5ca49adf) }

var fileDescriptor_net_6a797cde5ca49adf = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4b, 0x2d, 0xd1,
	0x4f, 0x2c, 0xc8, 0xd4, 0xcf, 0x4b, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f,
	0xca, 0xcc, 0xd7, 0xcb, 0x4b, 0x2d, 0x51, 0x72, 0xe7, 0x62, 0x0b, 0x28, 0x4a, 0x4d, 0xcb, 0xac,
	0x10, 0x52, 0xe5, 0x62, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x36, 0xe2, 0xd6, 0x83, 0x2a, 0xd2, 0xf3, 0x0c, 0x08, 0x82, 0xc9, 0x09, 0x89, 0x71, 0xb1,
	0x15, 0xa4, 0x55, 0xe4, 0xa4, 0xe6, 0x49, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0x41, 0x79, 0x4a,
	0x0d, 0x8c, 0x5c, 0x4c, 0x9e, 0x01, 0x20, 0xe9, 0x8c, 0xcc, 0xf4, 0x8c, 0xd4, 0x22, 0xb0, 0x21,
	0x2c, 0x41, 0x50, 0x9e, 0x90, 0x08, 0x17, 0x6b, 0x4e, 0x7e, 0x79, 0x6a, 0x11, 0x58, 0x17, 0x4b,
	0x10, 0x84, 0x23, 0xa4, 0xcb, 0xc5, 0x5e, 0x96, 0x5a, 0x54, 0x9c, 0x99, 0x9f, 0x27, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x67, 0x24, 0x8c, 0x64, 0xa7, 0x5e, 0x18, 0x44, 0x2a, 0x08, 0xa6, 0x46, 0x49,
	0x96, 0x8b, 0x1d, 0x2a, 0x26, 0xc4, 0xc1, 0xc5, 0xe2, 0x19, 0x50, 0x66, 0x22, 0xc0, 0x00, 0x65,
	0x99, 0x09, 0x30, 0x3a, 0x71, 0x46, 0xb1, 0x43, 0x7d, 0x9a, 0xc4, 0x06, 0xf6, 0xa6, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0xe8, 0xa8, 0x67, 0xfb, 0x00, 0x00, 0x00,
}
