// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route/api/route.proto

package api // import "route/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import api "net/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Path_Type int32

const (
	Path_Static Path_Type = 0
	Path_BGP    Path_Type = 1
)

var Path_Type_name = map[int32]string{
	0: "Static",
	1: "BGP",
}
var Path_Type_value = map[string]int32{
	"Static": 0,
	"BGP":    1,
}

func (x Path_Type) String() string {
	return proto.EnumName(Path_Type_name, int32(x))
}
func (Path_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{1, 0}
}

type Route struct {
	Pfx                  *api.Prefix `protobuf:"bytes,1,opt,name=pfx,proto3" json:"pfx,omitempty"`
	Paths                []*Path     `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{0}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (dst *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(dst, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPfx() *api.Prefix {
	if m != nil {
		return m.Pfx
	}
	return nil
}

func (m *Route) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Type                 Path_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=bio.route.Path_Type" json:"type,omitempty"`
	StaticPath           *StaticPath `protobuf:"bytes,2,opt,name=static_path,json=staticPath,proto3" json:"static_path,omitempty"`
	BGPPath              *BGPPath    `protobuf:"bytes,3,opt,name=BGP_path,json=BGPPath,proto3" json:"BGP_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{1}
}
func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (dst *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(dst, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetType() Path_Type {
	if m != nil {
		return m.Type
	}
	return Path_Static
}

func (m *Path) GetStaticPath() *StaticPath {
	if m != nil {
		return m.StaticPath
	}
	return nil
}

func (m *Path) GetBGPPath() *BGPPath {
	if m != nil {
		return m.BGPPath
	}
	return nil
}

type StaticPath struct {
	NextHop              *api.IP  `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticPath) Reset()         { *m = StaticPath{} }
func (m *StaticPath) String() string { return proto.CompactTextString(m) }
func (*StaticPath) ProtoMessage()    {}
func (*StaticPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{2}
}
func (m *StaticPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticPath.Unmarshal(m, b)
}
func (m *StaticPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticPath.Marshal(b, m, deterministic)
}
func (dst *StaticPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticPath.Merge(dst, src)
}
func (m *StaticPath) XXX_Size() int {
	return xxx_messageInfo_StaticPath.Size(m)
}
func (m *StaticPath) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticPath.DiscardUnknown(m)
}

var xxx_messageInfo_StaticPath proto.InternalMessageInfo

func (m *StaticPath) GetNextHop() *api.IP {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type BGPPath struct {
	PathIdentifier       uint32              `protobuf:"varint,1,opt,name=path_identifier,json=pathIdentifier,proto3" json:"path_identifier,omitempty"`
	NextHop              *api.IP             `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	LocalPref            uint32              `protobuf:"varint,3,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	ASPath               []*ASPathSegment    `protobuf:"bytes,4,rep,name=AS_path,json=ASPath,proto3" json:"AS_path,omitempty"`
	Origin               uint32              `protobuf:"varint,5,opt,name=origin,proto3" json:"origin,omitempty"`
	MED                  uint32              `protobuf:"varint,6,opt,name=MED,proto3" json:"MED,omitempty"`
	EBGP                 bool                `protobuf:"varint,7,opt,name=EBGP,proto3" json:"EBGP,omitempty"`
	BGPIdentifier        uint32              `protobuf:"varint,8,opt,name=BGP_identifier,json=BGPIdentifier,proto3" json:"BGP_identifier,omitempty"`
	Source               *api.IP             `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	Communities          []uint32            `protobuf:"varint,10,rep,packed,name=communities,proto3" json:"communities,omitempty"`
	LargeCommunities     []*LargeCommunity   `protobuf:"bytes,11,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	OriginatorId         uint32              `protobuf:"varint,12,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	ClusterList          []uint32            `protobuf:"varint,13,rep,packed,name=cluster_list,json=clusterList,proto3" json:"cluster_list,omitempty"`
	UnknownAttributes    []*UnknownAttribute `protobuf:"bytes,14,rep,name=unknown_attributes,json=unknownAttributes,proto3" json:"unknown_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BGPPath) Reset()         { *m = BGPPath{} }
func (m *BGPPath) String() string { return proto.CompactTextString(m) }
func (*BGPPath) ProtoMessage()    {}
func (*BGPPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{3}
}
func (m *BGPPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BGPPath.Unmarshal(m, b)
}
func (m *BGPPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BGPPath.Marshal(b, m, deterministic)
}
func (dst *BGPPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BGPPath.Merge(dst, src)
}
func (m *BGPPath) XXX_Size() int {
	return xxx_messageInfo_BGPPath.Size(m)
}
func (m *BGPPath) XXX_DiscardUnknown() {
	xxx_messageInfo_BGPPath.DiscardUnknown(m)
}

var xxx_messageInfo_BGPPath proto.InternalMessageInfo

func (m *BGPPath) GetPathIdentifier() uint32 {
	if m != nil {
		return m.PathIdentifier
	}
	return 0
}

func (m *BGPPath) GetNextHop() *api.IP {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *BGPPath) GetLocalPref() uint32 {
	if m != nil {
		return m.LocalPref
	}
	return 0
}

func (m *BGPPath) GetASPath() []*ASPathSegment {
	if m != nil {
		return m.ASPath
	}
	return nil
}

func (m *BGPPath) GetOrigin() uint32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *BGPPath) GetMED() uint32 {
	if m != nil {
		return m.MED
	}
	return 0
}

func (m *BGPPath) GetEBGP() bool {
	if m != nil {
		return m.EBGP
	}
	return false
}

func (m *BGPPath) GetBGPIdentifier() uint32 {
	if m != nil {
		return m.BGPIdentifier
	}
	return 0
}

func (m *BGPPath) GetSource() *api.IP {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *BGPPath) GetCommunities() []uint32 {
	if m != nil {
		return m.Communities
	}
	return nil
}

func (m *BGPPath) GetLargeCommunities() []*LargeCommunity {
	if m != nil {
		return m.LargeCommunities
	}
	return nil
}

func (m *BGPPath) GetOriginatorId() uint32 {
	if m != nil {
		return m.OriginatorId
	}
	return 0
}

func (m *BGPPath) GetClusterList() []uint32 {
	if m != nil {
		return m.ClusterList
	}
	return nil
}

func (m *BGPPath) GetUnknownAttributes() []*UnknownAttribute {
	if m != nil {
		return m.UnknownAttributes
	}
	return nil
}

type ASPathSegment struct {
	ASSequence           bool     `protobuf:"varint,1,opt,name=AS_sequence,json=ASSequence,proto3" json:"AS_sequence,omitempty"`
	ASNs                 []uint32 `protobuf:"varint,2,rep,packed,name=ASNs,proto3" json:"ASNs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASPathSegment) Reset()         { *m = ASPathSegment{} }
func (m *ASPathSegment) String() string { return proto.CompactTextString(m) }
func (*ASPathSegment) ProtoMessage()    {}
func (*ASPathSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{4}
}
func (m *ASPathSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASPathSegment.Unmarshal(m, b)
}
func (m *ASPathSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASPathSegment.Marshal(b, m, deterministic)
}
func (dst *ASPathSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASPathSegment.Merge(dst, src)
}
func (m *ASPathSegment) XXX_Size() int {
	return xxx_messageInfo_ASPathSegment.Size(m)
}
func (m *ASPathSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_ASPathSegment.DiscardUnknown(m)
}

var xxx_messageInfo_ASPathSegment proto.InternalMessageInfo

func (m *ASPathSegment) GetASSequence() bool {
	if m != nil {
		return m.ASSequence
	}
	return false
}

func (m *ASPathSegment) GetASNs() []uint32 {
	if m != nil {
		return m.ASNs
	}
	return nil
}

type LargeCommunity struct {
	GlobalAdministrator  uint32   `protobuf:"varint,1,opt,name=global_administrator,json=globalAdministrator,proto3" json:"global_administrator,omitempty"`
	DataPart1            uint32   `protobuf:"varint,2,opt,name=data_part1,json=dataPart1,proto3" json:"data_part1,omitempty"`
	DataPart2            uint32   `protobuf:"varint,3,opt,name=data_part2,json=dataPart2,proto3" json:"data_part2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeCommunity) Reset()         { *m = LargeCommunity{} }
func (m *LargeCommunity) String() string { return proto.CompactTextString(m) }
func (*LargeCommunity) ProtoMessage()    {}
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{5}
}
func (m *LargeCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeCommunity.Unmarshal(m, b)
}
func (m *LargeCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeCommunity.Marshal(b, m, deterministic)
}
func (dst *LargeCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeCommunity.Merge(dst, src)
}
func (m *LargeCommunity) XXX_Size() int {
	return xxx_messageInfo_LargeCommunity.Size(m)
}
func (m *LargeCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_LargeCommunity proto.InternalMessageInfo

func (m *LargeCommunity) GetGlobalAdministrator() uint32 {
	if m != nil {
		return m.GlobalAdministrator
	}
	return 0
}

func (m *LargeCommunity) GetDataPart1() uint32 {
	if m != nil {
		return m.DataPart1
	}
	return 0
}

func (m *LargeCommunity) GetDataPart2() uint32 {
	if m != nil {
		return m.DataPart2
	}
	return 0
}

type UnknownAttribute struct {
	Optional             bool     `protobuf:"varint,1,opt,name=optional,proto3" json:"optional,omitempty"`
	Transitive           bool     `protobuf:"varint,2,opt,name=transitive,proto3" json:"transitive,omitempty"`
	Partial              bool     `protobuf:"varint,3,opt,name=partial,proto3" json:"partial,omitempty"`
	TypeCode             uint32   `protobuf:"varint,4,opt,name=type_code,json=typeCode,proto3" json:"type_code,omitempty"`
	Value                []byte   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnknownAttribute) Reset()         { *m = UnknownAttribute{} }
func (m *UnknownAttribute) String() string { return proto.CompactTextString(m) }
func (*UnknownAttribute) ProtoMessage()    {}
func (*UnknownAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_route_5b7763c861ad4226, []int{6}
}
func (m *UnknownAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnknownAttribute.Unmarshal(m, b)
}
func (m *UnknownAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnknownAttribute.Marshal(b, m, deterministic)
}
func (dst *UnknownAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnknownAttribute.Merge(dst, src)
}
func (m *UnknownAttribute) XXX_Size() int {
	return xxx_messageInfo_UnknownAttribute.Size(m)
}
func (m *UnknownAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_UnknownAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_UnknownAttribute proto.InternalMessageInfo

func (m *UnknownAttribute) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *UnknownAttribute) GetTransitive() bool {
	if m != nil {
		return m.Transitive
	}
	return false
}

func (m *UnknownAttribute) GetPartial() bool {
	if m != nil {
		return m.Partial
	}
	return false
}

func (m *UnknownAttribute) GetTypeCode() uint32 {
	if m != nil {
		return m.TypeCode
	}
	return 0
}

func (m *UnknownAttribute) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "bio.route.Route")
	proto.RegisterType((*Path)(nil), "bio.route.Path")
	proto.RegisterType((*StaticPath)(nil), "bio.route.StaticPath")
	proto.RegisterType((*BGPPath)(nil), "bio.route.BGPPath")
	proto.RegisterType((*ASPathSegment)(nil), "bio.route.ASPathSegment")
	proto.RegisterType((*LargeCommunity)(nil), "bio.route.LargeCommunity")
	proto.RegisterType((*UnknownAttribute)(nil), "bio.route.UnknownAttribute")
	proto.RegisterEnum("bio.route.Path_Type", Path_Type_name, Path_Type_value)
}

func init() { proto.RegisterFile("route/api/route.proto", fileDescriptor_route_5b7763c861ad4226) }

var fileDescriptor_route_5b7763c861ad4226 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcd, 0x72, 0xd3, 0x3a,
	0x14, 0xbe, 0x69, 0xfe, 0x9c, 0x93, 0x38, 0x4d, 0xcf, 0x6d, 0xef, 0xf8, 0xb6, 0x03, 0xa4, 0xee,
	0x14, 0xb2, 0x21, 0x9d, 0x06, 0x86, 0x7d, 0xd2, 0x96, 0x50, 0xa6, 0x30, 0x46, 0x86, 0x0d, 0x1b,
	0x8f, 0x92, 0x28, 0xa9, 0x06, 0xc7, 0x32, 0xb6, 0x5c, 0xda, 0x25, 0xcf, 0xc1, 0x6b, 0xf4, 0x01,
	0x19, 0x49, 0x4e, 0xea, 0x94, 0x61, 0x77, 0xce, 0xf7, 0x9d, 0xbf, 0x4f, 0x3a, 0x12, 0xec, 0x25,
	0x22, 0x93, 0xec, 0x84, 0xc6, 0xfc, 0x44, 0x5b, 0xfd, 0x38, 0x11, 0x52, 0x60, 0x63, 0xc2, 0x45,
	0x5f, 0x03, 0xfb, 0x3b, 0x11, 0x93, 0x9a, 0x8f, 0x98, 0x34, 0xac, 0xfb, 0x09, 0xaa, 0x44, 0x71,
	0x78, 0x08, 0xe5, 0x78, 0x7e, 0xeb, 0x94, 0xba, 0xa5, 0x5e, 0x73, 0xb0, 0xdd, 0x57, 0x49, 0x2a,
	0xca, 0x4b, 0xd8, 0x9c, 0xdf, 0x12, 0xc5, 0xe1, 0x31, 0x54, 0x63, 0x2a, 0xaf, 0x53, 0x67, 0xab,
	0x5b, 0x5e, 0x07, 0x99, 0x56, 0x1e, 0x95, 0xd7, 0xc4, 0xb0, 0xee, 0x7d, 0x09, 0x2a, 0xca, 0xc7,
	0x1e, 0x54, 0xe4, 0x5d, 0xcc, 0x74, 0xcd, 0xf6, 0x60, 0xf7, 0x51, 0x78, 0xff, 0xf3, 0x5d, 0xcc,
	0x88, 0x8e, 0xc0, 0x37, 0xd0, 0x4c, 0x25, 0x95, 0x7c, 0x1a, 0xa8, 0x12, 0xce, 0x96, 0x1e, 0x62,
	0xaf, 0x90, 0xe0, 0x6b, 0x56, 0x77, 0x81, 0x74, 0x6d, 0xe3, 0x4b, 0xb0, 0x46, 0x63, 0xcf, 0x24,
	0x95, 0x75, 0x12, 0x16, 0x92, 0x46, 0x63, 0x4f, 0x67, 0xd4, 0x73, 0xc3, 0x3d, 0x80, 0x8a, 0x6a,
	0x8a, 0x00, 0x35, 0x53, 0xb0, 0xf3, 0x0f, 0xd6, 0xa1, 0x3c, 0x1a, 0x7b, 0x9d, 0x92, 0xfb, 0x1a,
	0xe0, 0xa1, 0x0b, 0x3e, 0x07, 0x2b, 0x62, 0xb7, 0x32, 0xb8, 0x16, 0x71, 0x7e, 0x26, 0xcd, 0xf5,
	0x99, 0x5c, 0x7a, 0xa4, 0xae, 0xc8, 0x77, 0x22, 0x76, 0xef, 0x2b, 0xb0, 0x2a, 0x8f, 0x2f, 0x60,
	0x5b, 0x4d, 0x12, 0xf0, 0x19, 0x8b, 0x24, 0x9f, 0x73, 0x96, 0xe8, 0x54, 0x9b, 0xb4, 0x15, 0x7c,
	0xb9, 0x46, 0x37, 0x8a, 0x6f, 0xfd, 0xbd, 0x38, 0x3e, 0x01, 0x08, 0xc5, 0x94, 0x86, 0x41, 0x9c,
	0xb0, 0xb9, 0x16, 0x68, 0x93, 0x86, 0x46, 0xd4, 0xb5, 0xe0, 0x29, 0xd4, 0x87, 0xbe, 0x11, 0x5f,
	0xd1, 0x37, 0xe2, 0x14, 0xc4, 0x0f, 0x7d, 0x35, 0x93, 0xcf, 0x16, 0x4b, 0x16, 0x49, 0x52, 0x33,
	0x2e, 0xfe, 0x07, 0x35, 0x91, 0xf0, 0x05, 0x8f, 0x9c, 0xaa, 0xae, 0x96, 0x7b, 0xd8, 0x81, 0xf2,
	0x87, 0x8b, 0x73, 0xa7, 0xa6, 0x41, 0x65, 0x22, 0x42, 0xe5, 0x62, 0x34, 0xf6, 0x9c, 0x7a, 0xb7,
	0xd4, 0xb3, 0x88, 0xb6, 0xf1, 0x18, 0xda, 0xea, 0xb8, 0x0b, 0xfa, 0x2c, 0x9d, 0x60, 0x8f, 0xc6,
	0x5e, 0x41, 0xde, 0x11, 0xd4, 0x52, 0x91, 0x25, 0x53, 0xe6, 0x34, 0xfe, 0x14, 0x97, 0x53, 0xd8,
	0x85, 0xe6, 0x54, 0x2c, 0x97, 0x59, 0xc4, 0x25, 0x67, 0xa9, 0x03, 0xdd, 0x72, 0xcf, 0x26, 0x45,
	0x08, 0xdf, 0xc2, 0x4e, 0x48, 0x93, 0x05, 0x0b, 0x8a, 0x71, 0x4d, 0x2d, 0xf4, 0xff, 0x82, 0xd0,
	0x2b, 0x15, 0x73, 0x96, 0x87, 0xdc, 0x91, 0x4e, 0x58, 0xf4, 0x55, 0x9d, 0x23, 0xb0, 0x8d, 0x4a,
	0x2a, 0x45, 0x12, 0xf0, 0x99, 0xd3, 0xd2, 0x43, 0xb7, 0x1e, 0xc0, 0xcb, 0x19, 0x1e, 0x42, 0x6b,
	0x1a, 0x66, 0xa9, 0x64, 0x49, 0x10, 0xf2, 0x54, 0x3a, 0x76, 0x3e, 0x8f, 0xc1, 0xae, 0x78, 0x2a,
	0xf1, 0x3d, 0x60, 0x16, 0x7d, 0x8b, 0xc4, 0x8f, 0x28, 0xa0, 0x52, 0x26, 0x7c, 0x92, 0x49, 0x96,
	0x3a, 0x6d, 0x3d, 0xd0, 0x41, 0x61, 0xa0, 0x2f, 0x26, 0x68, 0xb8, 0x8a, 0x21, 0x3b, 0xd9, 0x23,
	0x24, 0x75, 0xcf, 0xc1, 0xde, 0xb8, 0x20, 0x7c, 0x06, 0xcd, 0xa1, 0x1f, 0xa4, 0xec, 0x7b, 0xc6,
	0xa2, 0xa9, 0x79, 0x32, 0x16, 0x81, 0xa1, 0xef, 0xe7, 0x88, 0xba, 0x8f, 0xa1, 0xff, 0xd1, 0xbc,
	0x3d, 0x9b, 0x68, 0xdb, 0xfd, 0x59, 0x82, 0xf6, 0xa6, 0x7c, 0x3c, 0x85, 0xdd, 0x45, 0x28, 0x26,
	0x34, 0x0c, 0xe8, 0x6c, 0xc9, 0x23, 0x9e, 0xca, 0x44, 0x29, 0xcc, 0x17, 0xf1, 0x5f, 0xc3, 0x0d,
	0x8b, 0x94, 0xda, 0xb2, 0x19, 0x95, 0x34, 0x88, 0x69, 0x22, 0x4f, 0xf5, 0x3e, 0xda, 0xa4, 0xa1,
	0x10, 0x4f, 0x01, 0x1b, 0xf4, 0x60, 0xb5, 0x84, 0x2b, 0x7a, 0xe0, 0xfe, 0x2a, 0x41, 0xe7, 0xb1,
	0x62, 0xdc, 0x07, 0x4b, 0xc4, 0x92, 0x8b, 0x88, 0x86, 0xb9, 0x94, 0xb5, 0x8f, 0x4f, 0x01, 0x64,
	0x42, 0xa3, 0x94, 0x4b, 0x7e, 0xc3, 0x74, 0x3b, 0x8b, 0x14, 0x10, 0x74, 0xa0, 0xae, 0x5a, 0x71,
	0x1a, 0xea, 0x66, 0x16, 0x59, 0xb9, 0x78, 0x00, 0x0d, 0xf5, 0x5b, 0x04, 0x53, 0x31, 0x63, 0x4e,
	0x45, 0x0f, 0x62, 0x29, 0xe0, 0x4c, 0xcc, 0x18, 0xee, 0x42, 0xf5, 0x86, 0x86, 0x19, 0xd3, 0x8b,
	0xdd, 0x22, 0xc6, 0x19, 0x35, 0xbf, 0x36, 0xd6, 0xbf, 0xe2, 0xa4, 0xa6, 0xbf, 0xbc, 0x57, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x9d, 0x92, 0xdc, 0x29, 0x05, 0x00, 0x00,
}
