// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bio-routing/bio-rd/route/api/route.proto

/*
Package bio_route is a generated protocol buffer package.

It is generated from these files:
	github.com/bio-routing/bio-rd/route/api/route.proto

It has these top-level messages:
	Route
	Path
	StaticPath
	BGPPath
	ASPathSegment
	LargeCommunity
	UnknownAttribute
*/
package bio_route

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bio_net "github.com/bio-routing/bio-rd/net/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	Pfx   *bio_net.Prefix `protobuf:"bytes,1,opt,name=pfx" json:"pfx,omitempty"`
	Paths []*Path         `protobuf:"bytes,2,rep,name=paths" json:"paths,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Route) GetPfx() *bio_net.Prefix {
	if m != nil {
		return m.Pfx
	}
	return nil
}

func (m *Route) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Type       uint32      `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	BGPPath    *BGPPath    `protobuf:"bytes,2,opt,name=BGP_path,json=BGPPath" json:"BGP_path,omitempty"`
	StaticPath *StaticPath `protobuf:"bytes,3,opt,name=static_path,json=staticPath" json:"static_path,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Path) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Path) GetBGPPath() *BGPPath {
	if m != nil {
		return m.BGPPath
	}
	return nil
}

func (m *Path) GetStaticPath() *StaticPath {
	if m != nil {
		return m.StaticPath
	}
	return nil
}

type StaticPath struct {
	NextHop *bio_net.IP `protobuf:"bytes,1,opt,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
}

func (m *StaticPath) Reset()                    { *m = StaticPath{} }
func (m *StaticPath) String() string            { return proto.CompactTextString(m) }
func (*StaticPath) ProtoMessage()               {}
func (*StaticPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StaticPath) GetNextHop() *bio_net.IP {
	if m != nil {
		return m.NextHop
	}
	return nil
}

type BGPPath struct {
	PathIdentifier    uint32              `protobuf:"varint,1,opt,name=path_identifier,json=pathIdentifier" json:"path_identifier,omitempty"`
	NextHop           *bio_net.IP         `protobuf:"bytes,2,opt,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
	LocalPref         uint32              `protobuf:"varint,3,opt,name=local_pref,json=localPref" json:"local_pref,omitempty"`
	ASPath            []*ASPathSegment    `protobuf:"bytes,4,rep,name=AS_path,json=ASPath" json:"AS_path,omitempty"`
	Origin            uint32              `protobuf:"varint,5,opt,name=origin" json:"origin,omitempty"`
	MED               uint32              `protobuf:"varint,6,opt,name=MED" json:"MED,omitempty"`
	EBGP              bool                `protobuf:"varint,7,opt,name=EBGP" json:"EBGP,omitempty"`
	BGPIdentifier     uint32              `protobuf:"varint,8,opt,name=BGP_identifier,json=BGPIdentifier" json:"BGP_identifier,omitempty"`
	Source            *bio_net.IP         `protobuf:"bytes,9,opt,name=source" json:"source,omitempty"`
	Communities       []uint32            `protobuf:"varint,10,rep,packed,name=communities" json:"communities,omitempty"`
	LargeCommunities  []*LargeCommunity   `protobuf:"bytes,11,rep,name=large_communities,json=largeCommunities" json:"large_communities,omitempty"`
	OriginatorId      uint32              `protobuf:"varint,12,opt,name=originator_id,json=originatorId" json:"originator_id,omitempty"`
	ClusterList       []uint32            `protobuf:"varint,13,rep,packed,name=cluster_list,json=clusterList" json:"cluster_list,omitempty"`
	UnknownAttributes []*UnknownAttribute `protobuf:"bytes,14,rep,name=unknown_attributes,json=unknownAttributes" json:"unknown_attributes,omitempty"`
}

func (m *BGPPath) Reset()                    { *m = BGPPath{} }
func (m *BGPPath) String() string            { return proto.CompactTextString(m) }
func (*BGPPath) ProtoMessage()               {}
func (*BGPPath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BGPPath) GetPathIdentifier() uint32 {
	if m != nil {
		return m.PathIdentifier
	}
	return 0
}

func (m *BGPPath) GetNextHop() *bio_net.IP {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *BGPPath) GetLocalPref() uint32 {
	if m != nil {
		return m.LocalPref
	}
	return 0
}

func (m *BGPPath) GetASPath() []*ASPathSegment {
	if m != nil {
		return m.ASPath
	}
	return nil
}

func (m *BGPPath) GetOrigin() uint32 {
	if m != nil {
		return m.Origin
	}
	return 0
}

func (m *BGPPath) GetMED() uint32 {
	if m != nil {
		return m.MED
	}
	return 0
}

func (m *BGPPath) GetEBGP() bool {
	if m != nil {
		return m.EBGP
	}
	return false
}

func (m *BGPPath) GetBGPIdentifier() uint32 {
	if m != nil {
		return m.BGPIdentifier
	}
	return 0
}

func (m *BGPPath) GetSource() *bio_net.IP {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *BGPPath) GetCommunities() []uint32 {
	if m != nil {
		return m.Communities
	}
	return nil
}

func (m *BGPPath) GetLargeCommunities() []*LargeCommunity {
	if m != nil {
		return m.LargeCommunities
	}
	return nil
}

func (m *BGPPath) GetOriginatorId() uint32 {
	if m != nil {
		return m.OriginatorId
	}
	return 0
}

func (m *BGPPath) GetClusterList() []uint32 {
	if m != nil {
		return m.ClusterList
	}
	return nil
}

func (m *BGPPath) GetUnknownAttributes() []*UnknownAttribute {
	if m != nil {
		return m.UnknownAttributes
	}
	return nil
}

type ASPathSegment struct {
	ASSequence bool     `protobuf:"varint,1,opt,name=AS_sequence,json=ASSequence" json:"AS_sequence,omitempty"`
	ASNs       []uint32 `protobuf:"varint,2,rep,packed,name=ASNs" json:"ASNs,omitempty"`
}

func (m *ASPathSegment) Reset()                    { *m = ASPathSegment{} }
func (m *ASPathSegment) String() string            { return proto.CompactTextString(m) }
func (*ASPathSegment) ProtoMessage()               {}
func (*ASPathSegment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ASPathSegment) GetASSequence() bool {
	if m != nil {
		return m.ASSequence
	}
	return false
}

func (m *ASPathSegment) GetASNs() []uint32 {
	if m != nil {
		return m.ASNs
	}
	return nil
}

type LargeCommunity struct {
	GlobalAdministrator uint32 `protobuf:"varint,1,opt,name=global_administrator,json=globalAdministrator" json:"global_administrator,omitempty"`
	DataPart1           uint32 `protobuf:"varint,2,opt,name=data_part1,json=dataPart1" json:"data_part1,omitempty"`
	DataPart2           uint32 `protobuf:"varint,3,opt,name=data_part2,json=dataPart2" json:"data_part2,omitempty"`
}

func (m *LargeCommunity) Reset()                    { *m = LargeCommunity{} }
func (m *LargeCommunity) String() string            { return proto.CompactTextString(m) }
func (*LargeCommunity) ProtoMessage()               {}
func (*LargeCommunity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LargeCommunity) GetGlobalAdministrator() uint32 {
	if m != nil {
		return m.GlobalAdministrator
	}
	return 0
}

func (m *LargeCommunity) GetDataPart1() uint32 {
	if m != nil {
		return m.DataPart1
	}
	return 0
}

func (m *LargeCommunity) GetDataPart2() uint32 {
	if m != nil {
		return m.DataPart2
	}
	return 0
}

type UnknownAttribute struct {
	Optional   bool   `protobuf:"varint,1,opt,name=optional" json:"optional,omitempty"`
	Transitive bool   `protobuf:"varint,2,opt,name=transitive" json:"transitive,omitempty"`
	Partial    bool   `protobuf:"varint,3,opt,name=partial" json:"partial,omitempty"`
	TypeCode   uint32 `protobuf:"varint,4,opt,name=type_code,json=typeCode" json:"type_code,omitempty"`
	Value      []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *UnknownAttribute) Reset()                    { *m = UnknownAttribute{} }
func (m *UnknownAttribute) String() string            { return proto.CompactTextString(m) }
func (*UnknownAttribute) ProtoMessage()               {}
func (*UnknownAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UnknownAttribute) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

func (m *UnknownAttribute) GetTransitive() bool {
	if m != nil {
		return m.Transitive
	}
	return false
}

func (m *UnknownAttribute) GetPartial() bool {
	if m != nil {
		return m.Partial
	}
	return false
}

func (m *UnknownAttribute) GetTypeCode() uint32 {
	if m != nil {
		return m.TypeCode
	}
	return 0
}

func (m *UnknownAttribute) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "bio.route.Route")
	proto.RegisterType((*Path)(nil), "bio.route.Path")
	proto.RegisterType((*StaticPath)(nil), "bio.route.StaticPath")
	proto.RegisterType((*BGPPath)(nil), "bio.route.BGPPath")
	proto.RegisterType((*ASPathSegment)(nil), "bio.route.ASPathSegment")
	proto.RegisterType((*LargeCommunity)(nil), "bio.route.LargeCommunity")
	proto.RegisterType((*UnknownAttribute)(nil), "bio.route.UnknownAttribute")
}

func init() {
	proto.RegisterFile("github.com/bio-routing/bio-rd/route/api/route.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5d, 0x4f, 0xdb, 0x3c,
	0x14, 0x56, 0xe9, 0x57, 0x7a, 0xda, 0x14, 0xf0, 0xcb, 0xfb, 0x2a, 0x2f, 0x68, 0x5b, 0x29, 0x62,
	0xe3, 0x86, 0x56, 0xc0, 0xb4, 0xfb, 0x16, 0x58, 0xc7, 0xc4, 0xa6, 0xcc, 0xd1, 0xae, 0x23, 0x37,
	0x71, 0x5b, 0x6b, 0xa9, 0x9d, 0x39, 0x0e, 0x83, 0xcb, 0xfd, 0x8e, 0xfd, 0x8d, 0xfd, 0xc0, 0xc9,
	0x76, 0x5a, 0x52, 0xa6, 0xed, 0xee, 0x9c, 0xe7, 0x39, 0x5f, 0x4f, 0xce, 0x89, 0xe1, 0x62, 0xce,
	0xd4, 0x22, 0x9f, 0x0e, 0x22, 0xb1, 0x1c, 0x4e, 0x99, 0x38, 0x95, 0x22, 0x57, 0x8c, 0xcf, 0xad,
	0x1d, 0x0f, 0xb5, 0x4b, 0x87, 0x24, 0x65, 0xd6, 0x1a, 0xa4, 0x52, 0x28, 0x81, 0x5a, 0x53, 0x26,
	0x06, 0x06, 0xd8, 0x1f, 0xfe, 0x3d, 0x9f, 0x53, 0x65, 0xb2, 0x39, 0x55, 0x36, 0xb7, 0xff, 0x09,
	0xea, 0x58, 0x67, 0xa2, 0x43, 0xa8, 0xa6, 0xb3, 0x7b, 0xaf, 0xd2, 0xab, 0x9c, 0xb4, 0xcf, 0xb7,
	0x07, 0xba, 0xa4, 0x8e, 0xf2, 0x25, 0x9d, 0xb1, 0x7b, 0xac, 0x39, 0x74, 0x0c, 0xf5, 0x94, 0xa8,
	0x45, 0xe6, 0x6d, 0xf5, 0xaa, 0xeb, 0x20, 0x3b, 0x88, 0x4f, 0xd4, 0x02, 0x5b, 0xb6, 0xff, 0xbd,
	0x02, 0x35, 0xed, 0x23, 0x04, 0x35, 0xf5, 0x90, 0x52, 0x53, 0xd3, 0xc5, 0xc6, 0x46, 0xa7, 0xe0,
	0x8c, 0x27, 0x7e, 0xa8, 0x23, 0xbd, 0x2d, 0xd3, 0x0b, 0x95, 0xca, 0x8c, 0x27, 0xbe, 0xa9, 0xd4,
	0x2c, 0x0c, 0xf4, 0x06, 0xda, 0x99, 0x22, 0x8a, 0x45, 0x36, 0xa3, 0x6a, 0x32, 0xfe, 0x2d, 0x65,
	0x04, 0x86, 0x35, 0x49, 0x90, 0xad, 0xed, 0xfe, 0x6b, 0x80, 0x47, 0x06, 0xbd, 0x04, 0x87, 0xd3,
	0x7b, 0x15, 0x2e, 0x44, 0x5a, 0x08, 0x6c, 0xaf, 0x05, 0xde, 0xf8, 0xb8, 0xa9, 0xc9, 0x77, 0x22,
	0xed, 0xff, 0xac, 0xc1, 0xba, 0xf3, 0x2b, 0xd8, 0xd6, 0x2d, 0x43, 0x16, 0x53, 0xae, 0xd8, 0x8c,
	0x51, 0x59, 0xe8, 0xe8, 0x6a, 0xf8, 0x66, 0x8d, 0x6e, 0x14, 0xdf, 0xfa, 0x73, 0x71, 0xf4, 0x0c,
	0x20, 0x11, 0x11, 0x49, 0xc2, 0x54, 0xd2, 0x99, 0x51, 0xe2, 0xe2, 0x96, 0x41, 0xf4, 0x37, 0x46,
	0x67, 0xd0, 0x1c, 0x05, 0x56, 0x65, 0xcd, 0x7c, 0x5e, 0xaf, 0xa4, 0x72, 0x14, 0xe8, 0x99, 0x02,
	0x3a, 0x5f, 0x52, 0xae, 0x70, 0xc3, 0xba, 0xe8, 0x3f, 0x68, 0x08, 0xc9, 0xe6, 0x8c, 0x7b, 0x75,
	0x53, 0xad, 0xf0, 0xd0, 0x0e, 0x54, 0x3f, 0x5c, 0x5f, 0x79, 0x0d, 0x03, 0x6a, 0x53, 0x6f, 0xe2,
	0x7a, 0x3c, 0xf1, 0xbd, 0x66, 0xaf, 0x72, 0xe2, 0x60, 0x63, 0xa3, 0x63, 0xe8, 0xea, 0x4d, 0x94,
	0xf4, 0x39, 0x26, 0xc1, 0x1d, 0x4f, 0xfc, 0x92, 0xbc, 0x23, 0x68, 0x64, 0x22, 0x97, 0x11, 0xf5,
	0x5a, 0xbf, 0x8b, 0x2b, 0x28, 0xd4, 0x83, 0x76, 0x24, 0x96, 0xcb, 0x9c, 0x33, 0xc5, 0x68, 0xe6,
	0x41, 0xaf, 0x7a, 0xe2, 0xe2, 0x32, 0x84, 0xde, 0xc2, 0x6e, 0x42, 0xe4, 0x9c, 0x86, 0xe5, 0xb8,
	0xb6, 0x11, 0xfa, 0x7f, 0x49, 0xe8, 0xad, 0x8e, 0xb9, 0x2c, 0x42, 0x1e, 0xf0, 0x4e, 0x52, 0xf6,
	0x75, 0x9d, 0x23, 0x70, 0xad, 0x4a, 0xa2, 0x84, 0x0c, 0x59, 0xec, 0x75, 0xcc, 0xd0, 0x9d, 0x47,
	0xf0, 0x26, 0x46, 0x87, 0xd0, 0x89, 0x92, 0x3c, 0x53, 0x54, 0x86, 0x09, 0xcb, 0x94, 0xe7, 0x16,
	0xf3, 0x58, 0xec, 0x96, 0x65, 0x0a, 0xbd, 0x07, 0x94, 0xf3, 0x2f, 0x5c, 0x7c, 0xe3, 0x21, 0x51,
	0x4a, 0xb2, 0x69, 0xae, 0x68, 0xe6, 0x75, 0xcd, 0x40, 0x07, 0xa5, 0x81, 0x3e, 0xdb, 0xa0, 0xd1,
	0x2a, 0x06, 0xef, 0xe6, 0x4f, 0x90, 0xac, 0x7f, 0x05, 0xee, 0xc6, 0x82, 0xd0, 0x0b, 0x68, 0x8f,
	0x82, 0x30, 0xa3, 0x5f, 0x73, 0xca, 0x23, 0x7b, 0xff, 0x0e, 0x86, 0x51, 0x10, 0x14, 0x88, 0xde,
	0xc7, 0x28, 0xf8, 0x68, 0x7f, 0x24, 0x17, 0x1b, 0x5b, 0xff, 0x36, 0xdd, 0x4d, 0xf9, 0xe8, 0x0c,
	0xf6, 0xe6, 0x89, 0x98, 0x92, 0x24, 0x24, 0xf1, 0x92, 0x71, 0x96, 0x29, 0xa9, 0x15, 0x16, 0x87,
	0xf8, 0x8f, 0xe5, 0x46, 0x65, 0x4a, 0x5f, 0x59, 0x4c, 0x14, 0x09, 0x53, 0x22, 0xd5, 0x99, 0xb9,
	0x47, 0x17, 0xb7, 0x34, 0xe2, 0x6b, 0x60, 0x83, 0x3e, 0x5f, 0x1d, 0xe1, 0x8a, 0x3e, 0xef, 0xff,
	0xa8, 0xc0, 0xce, 0x53, 0xc5, 0x68, 0x1f, 0x1c, 0x91, 0x2a, 0x26, 0x38, 0x49, 0x0a, 0x29, 0x6b,
	0x1f, 0x3d, 0x07, 0x50, 0x92, 0xf0, 0x8c, 0x29, 0x76, 0x47, 0x4d, 0x3b, 0x07, 0x97, 0x10, 0xe4,
	0x41, 0x53, 0xb7, 0x62, 0x24, 0x31, 0xcd, 0x1c, 0xbc, 0x72, 0xd1, 0x01, 0xb4, 0xf4, 0x83, 0x10,
	0x46, 0x22, 0xa6, 0x5e, 0xcd, 0x0c, 0xe2, 0x68, 0xe0, 0x52, 0xc4, 0x14, 0xed, 0x41, 0xfd, 0x8e,
	0x24, 0x39, 0x35, 0x87, 0xdd, 0xc1, 0xd6, 0x99, 0x36, 0xcc, 0x93, 0x75, 0xf1, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0xe9, 0x5f, 0x53, 0x36, 0x25, 0x05, 0x00, 0x00,
}
